services:
  postgres:
    image: postgres:16
    container_name: stockai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockai
    ports:
      - "5432:5432"
    volumes:
      - stockai_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: stockai-redis
    ports:
      - "6379:6379"

volumes:
  stockai_pgdata:
